### ISSUE TITLE
Upgrade flutter and use Null-Safety

### ISSUE THREAD

**Issue by javaherisaber** [mwaylabs/flutter-zebra-datawedge#1]
Can you upgrade Flutter version and support for Null-Safety?

**Comment by javaherisaber** [comment]
@me-mway 
I created a pull request regarding this issue here: https://github.com/mwaylabs/flutter-zebra-datawedge/pull/2

**Comment by danielkono** [comment]
Hey,
i will check the PR and update this package but also i will flag it as discontinued.
Since i have no access to Zebra devices anymore and also this package can be easily replaced by an `intent` package it makes no sense for me to maintain it.
